# Site settings
title: Ted Yu
SEOTitle: Ted Yu
header-img: img/home-bg.jpg
email: ted0426244568@outlook.com
description: "I’m Ted, a graduate with a master’s degree in Data Science from the University of Queensland, Australia. I have a strong passion for programming, data conslidation, modeling, and visual presentation. With my academic background and practical experience, I am committed to tackling complex data problems, extracting valuable insights from data, and presenting them in a clear and engaging manner for diverse audiences. My goal is to continually grow in the field of data science, explore new opportunities, and better understand and address real-world challenges."
keyword: "Ted, Data Science, University of Queensland, Programming, Data Conslidation, Modeling, Visual Presentation, Python, MySQL, PHP, Java, Tableau"
url: "https://teddata.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
linkedin_username:  Peng-Yu-ted0426244568
facebook_username:  ted.yu.9803
github_username: TedData
#twitter_username: huxpro

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "The Dance of Data, Insight into Tomorrow"
sidebar-avatar: "img/about_me.JPG" # https://github.com/Huxpro.png use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

